name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        env:
            EMAILUSERNAME: ${{ secrets.EMAILUSERNAME }}
            EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
        run: |
          yarn run build
          gh-pages -d build
